/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.qlnh.gui.dish;

import bkap.qlnh.dao.DishDAOImp;
import bkap.qlnh.dao.DrinkDAOImp;
import bkap.qlnh.dao.MenuDAOImp;
import bkap.qlnh.entities.Dish;
import bkap.qlnh.entities.Drink;
import bkap.qlnh.entities.Menu;
import bkap.qlnh.gui.mainframe.IFDelete;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ntan2
 */
public class IFMenu extends javax.swing.JInternalFrame implements IFDelete.CallbackDelete, IFAddDish.CallbackAdd, IFEditDish.CallbackEdit,
        IFRemoveDish.CallbackDelete, IFFindDish.CallbackFindDish, IFAddDrink.CallbackAdd, IFEditDrink.CallbackEdit, IFRemoveDrink.CallbackDelete, IFFindDrink.CallbackFindDrink {

    Menu m;
    MenuDAOImp menuDAO;
    Dish dish;
    DishDAOImp dishDAO;
    Drink drink;
    DrinkDAOImp drinkDAO;
    int menuId;
    int dishId;
    int drinkId;

    /**
     * Creates new form IFMenu
     */
    public IFMenu() {
        initComponents();
        setLocation(300, 50);
        loadMenuList();
        tblMenu.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                menuDetail();
            }
        });
        loadDishList(null);
        loadDrinkList(null);
    }

    private void loadMenuList() {
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);
        menuDAO = new MenuDAOImp();
        List<Menu> lstMenu = new ArrayList<>(menuDAO.lstMenu());
        for (Menu m : lstMenu) {
            String status = "";
            if (m.isStatus()) {
                status = "Còn";
            } else {
                status = "Hết";
            }
            model.addRow(new Object[]{m.getId(), m.getName(), status});
        }
        tblMenu.setModel(model);
    }

    private void loadDishList(String name) {
        DefaultTableModel model = (DefaultTableModel) tblDish.getModel();
        model.setRowCount(0);
        dishDAO = new DishDAOImp();
        List<Dish> lstDish = new ArrayList<>(dishDAO.lstDish(name));
        for (Dish d : lstDish) {
            String status = "";
            if (d.isStatus()) {
                status = "Còn";
            } else {
                status = "Hết";
            }
            model.addRow(new Object[]{d.getId(), d.getMenuName(), d.getName(), d.getPrice(), status});
        }
        tblDish.setModel(model);
    }

    private void loadDrinkList(String name) {
        DefaultTableModel model = (DefaultTableModel) tblDrink.getModel();
        model.setRowCount(0);
        drinkDAO = new DrinkDAOImp();
        List<Drink> lstDrink = new ArrayList<>(drinkDAO.lstDrink(name));
        for (Drink d : lstDrink) {
            String status = "";
            if (d.isStatus() == true) {
                status = "Còn";
            } else {
                status = "Hết";
            }
            model.addRow(new Object[]{d.getId(), d.getMenuName(), d.getName(), d.getPrice(), status});
        }
        tblDrink.setModel(model);
    }

    private void menuDetail() {
        int selectRow = tblMenu.getSelectedRow();
        if (selectRow >= 0) {
            int id = (int) tblMenu.getValueAt(selectRow, 0);
            m = new Menu();
            menuDAO = new MenuDAOImp();
            m = menuDAO.find(id);
            txtName.setText(m.getName());
            if (m.isStatus()) {
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton2.setSelected(true);
            }
            this.menuId = m.getId();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnMenuAdd = new javax.swing.JButton();
        btnMenuEdit = new javax.swing.JButton();
        btnMenuRemove = new javax.swing.JButton();
        btnMenuLoad = new javax.swing.JButton();
        lbMess = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDish = new javax.swing.JTable();
        btnDishAdd = new javax.swing.JButton();
        btnDishEdit = new javax.swing.JButton();
        btnDishRemove = new javax.swing.JButton();
        btnDishLoad = new javax.swing.JButton();
        btnDishFind = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDrink = new javax.swing.JTable();
        btnDrinkAdd = new javax.swing.JButton();
        btnDrinkEdit = new javax.swing.JButton();
        btnDrinkRemove = new javax.swing.JButton();
        btnDrinkLoad = new javax.swing.JButton();
        btnDrinkFind = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Mục");

        jPanel4.setBackground(new java.awt.Color(240, 240, 151));

        jLabel2.setText("Tên: ");

        jLabel3.setText("Trạng Thái:");

        jRadioButton1.setBackground(new java.awt.Color(240, 240, 169));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Còn");

        jRadioButton2.setBackground(new java.awt.Color(240, 240, 169));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Hết");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btnMenuAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenuAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_add_new_32px_1.png"))); // NOI18N
        btnMenuAdd.setText("Thêm");
        btnMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAddActionPerformed(evt);
            }
        });

        btnMenuEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenuEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_edit_property_32px.png"))); // NOI18N
        btnMenuEdit.setText("Sửa");
        btnMenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditActionPerformed(evt);
            }
        });

        btnMenuRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenuRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_shopping_basket_remove_32px.png"))); // NOI18N
        btnMenuRemove.setText("Xóa");
        btnMenuRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRemoveActionPerformed(evt);
            }
        });

        btnMenuLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMenuLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_reset_32px.png"))); // NOI18N
        btnMenuLoad.setText("Tải Lại");
        btnMenuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLoadActionPerformed(evt);
            }
        });

        lbMess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMess.setForeground(new java.awt.Color(252, 25, 25));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbMess, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnMenuAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenuEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenuRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMenuLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMess, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuAdd)
                    .addComponent(btnMenuEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(240, 240, 169));

        tblMenu.setBackground(new java.awt.Color(255, 248, 203));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(141, 218, 146));

        jPanel7.setBackground(new java.awt.Color(169, 247, 174));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Món Ăn");

        tblDish.setBackground(new java.awt.Color(38, 206, 92));
        tblDish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Danh Mục", "Tên", "Giá", "Trạng Thái"
            }
        ));
        jScrollPane2.setViewportView(tblDish);

        btnDishAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDishAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_add_new_32px_1.png"))); // NOI18N
        btnDishAdd.setText("Thêm");
        btnDishAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishAddActionPerformed(evt);
            }
        });

        btnDishEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDishEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_edit_property_32px.png"))); // NOI18N
        btnDishEdit.setText("Sửa");
        btnDishEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishEditActionPerformed(evt);
            }
        });

        btnDishRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDishRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_shopping_basket_remove_32px.png"))); // NOI18N
        btnDishRemove.setText("Xóa");
        btnDishRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishRemoveActionPerformed(evt);
            }
        });

        btnDishLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDishLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_reset_32px.png"))); // NOI18N
        btnDishLoad.setText("Tải Lại");
        btnDishLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishLoadActionPerformed(evt);
            }
        });

        btnDishFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDishFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_Find_iPhone_32px.png"))); // NOI18N
        btnDishFind.setText("Tìm Kiếm");
        btnDishFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnDishAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDishEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDishRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDishLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDishFind)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDishAdd)
                    .addComponent(btnDishEdit)
                    .addComponent(btnDishRemove)
                    .addComponent(btnDishLoad)
                    .addComponent(btnDishFind))
                .addGap(297, 297, 297))
        );

        jPanel8.setBackground(new java.awt.Color(169, 247, 174));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đồ Uống");

        tblDrink.setBackground(new java.awt.Color(109, 245, 149));
        tblDrink.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Danh Mục", "Tên", "Giá", "Trạng Thái"
            }
        ));
        jScrollPane3.setViewportView(tblDrink);

        btnDrinkAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDrinkAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_add_new_32px_1.png"))); // NOI18N
        btnDrinkAdd.setText("Thêm");
        btnDrinkAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkAddActionPerformed(evt);
            }
        });

        btnDrinkEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDrinkEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_edit_property_32px.png"))); // NOI18N
        btnDrinkEdit.setText("Sửa");
        btnDrinkEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkEditActionPerformed(evt);
            }
        });

        btnDrinkRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDrinkRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_shopping_basket_remove_32px.png"))); // NOI18N
        btnDrinkRemove.setText("Xóa");
        btnDrinkRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkRemoveActionPerformed(evt);
            }
        });

        btnDrinkLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDrinkLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_reset_32px.png"))); // NOI18N
        btnDrinkLoad.setText("Tải Lại");
        btnDrinkLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkLoadActionPerformed(evt);
            }
        });

        btnDrinkFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDrinkFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_Find_iPhone_32px.png"))); // NOI18N
        btnDrinkFind.setText("Tìm Kiếm");
        btnDrinkFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnDrinkAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrinkEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrinkRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrinkLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDrinkFind)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrinkAdd)
                    .addComponent(btnDrinkEdit)
                    .addComponent(btnDrinkRemove)
                    .addComponent(btnDrinkLoad)
                    .addComponent(btnDrinkFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnDishFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishFindActionPerformed
        IFFindDish IFD = new IFFindDish(true, this);
        IFD.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnDishFindActionPerformed

    private void btnMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAddActionPerformed
        String name = txtName.getText();
        boolean status = true;
        if (jRadioButton1.isSelected()) {
            status = true;
        } else {
            status = false;
        }
        m = new Menu(name, status);
        if (txtName.getText().trim().isEmpty()) {
            lbMess.setText("Không được để trống các trường");
        } else {
            menuDAO.add(m);
            loadMenuList();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuAddActionPerformed

    private void btnMenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditActionPerformed
        if (txtName.getText().trim().isEmpty()) {
            lbMess.setText("Không được để trống các trường");
        } else {
            m = new Menu();
            menuDAO = new MenuDAOImp();
            m.setId(this.menuId);
            m.setName(txtName.getText());
            m.setStatus(jRadioButton1.isSelected());
            menuDAO.edit(m);
            loadMenuList();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuEditActionPerformed

    private void btnMenuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLoadActionPerformed
        txtName.setText("");
        lbMess.setText(" ");
        JOptionPane.showMessageDialog(null, "Tải mới thành công");
// TODO add your handling code here:
    }//GEN-LAST:event_btnMenuLoadActionPerformed

    private void btnMenuRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRemoveActionPerformed
        // TODO add your handling code here:
        IFDelete IFD = new IFDelete(true, this);
        IFD.setVisible(true);
    }//GEN-LAST:event_btnMenuRemoveActionPerformed

    private void btnDishAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishAddActionPerformed
        IFAddDish IFAD = new IFAddDish(true, this);
        IFAD.setVisible(true);
    }//GEN-LAST:event_btnDishAddActionPerformed

    private void btnDishEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishEditActionPerformed
        int dishId = (int) tblDish.getValueAt(tblDish.getSelectedRow(), 0);
        IFEditDish IFE = new IFEditDish(true, this, dishId);
        IFE.setVisible(true);
        this.dishId = dishId;

// TODO add your handling code here:
    }//GEN-LAST:event_btnDishEditActionPerformed

    private void btnDishRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishRemoveActionPerformed
        IFRemoveDish IFR = new IFRemoveDish(true, this);
        IFR.setVisible(true);
    }//GEN-LAST:event_btnDishRemoveActionPerformed

    private void btnDishLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishLoadActionPerformed
        loadDishList(null);
        JOptionPane.showMessageDialog(null, "Làm mới thành công");

// TODO add your handling code here:
    }//GEN-LAST:event_btnDishLoadActionPerformed

    private void btnDrinkAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkAddActionPerformed
        IFAddDrink IFAD = new IFAddDrink(true, this);
        IFAD.setVisible(true);
        loadDrinkList(null);
// TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkAddActionPerformed

    private void btnDrinkEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkEditActionPerformed
        int drinkId = (int) tblDrink.getValueAt(tblDrink.getSelectedRow(), 0);
        IFEditDrink IFE = new IFEditDrink(true, this, drinkId);
        IFE.setVisible(true);
        this.drinkId = drinkId;
// TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkEditActionPerformed

    private void btnDrinkRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkRemoveActionPerformed
        IFRemoveDrink IFR = new IFRemoveDrink(true, this);
        IFR.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkRemoveActionPerformed

    private void btnDrinkLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkLoadActionPerformed
        loadDrinkList(null);
        JOptionPane.showMessageDialog(null, "Làm mới thành công");
    }//GEN-LAST:event_btnDrinkLoadActionPerformed

    private void btnDrinkFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkFindActionPerformed
        IFFindDrink IFD = new IFFindDrink(true, this);
        IFD.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDrinkFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDishAdd;
    private javax.swing.JButton btnDishEdit;
    private javax.swing.JButton btnDishFind;
    private javax.swing.JButton btnDishLoad;
    private javax.swing.JButton btnDishRemove;
    private javax.swing.JButton btnDrinkAdd;
    private javax.swing.JButton btnDrinkEdit;
    private javax.swing.JButton btnDrinkFind;
    private javax.swing.JButton btnDrinkLoad;
    private javax.swing.JButton btnDrinkRemove;
    private javax.swing.JButton btnMenuAdd;
    private javax.swing.JButton btnMenuEdit;
    private javax.swing.JButton btnMenuLoad;
    private javax.swing.JButton btnMenuRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbMess;
    private javax.swing.JTable tblDish;
    private javax.swing.JTable tblDrink;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doDelete(int id) {
        menuDAO = new MenuDAOImp();
        menuDAO.remove(this.menuId);
        loadMenuList();
    }

    @Override
    public void doAdd(JTextField txtDishName, JTextField txtDishPrice, JComboBox<Menu> cbxDish, JRadioButton dishStatus1, JRadioButton dishStatus2) {
        String name = txtDishName.getText();
        float price = Float.parseFloat(txtDishPrice.getText());
        int menuId = ((Menu) cbxDish.getSelectedItem()).getId();
        boolean status = true;
        if (dishStatus1.isSelected()) {
            status = true;
        } else {
            status = false;
        }
        dish = new Dish(name, price, menuId, status);
        dishDAO = new DishDAOImp();
        dishDAO.add(dish);
        loadDishList(null);
    }

    @Override
    public void doEdit(int id, JTextField txtName, JTextField txtPrice, JComboBox<Menu> cbxDish, JRadioButton dishStatus1, JRadioButton dishStatus2) {
        dish = new Dish();
        dishDAO = new DishDAOImp();
        dish.setId(this.dishId);
        dish.setName(txtName.getText());
        dish.setPrice(Float.parseFloat(txtPrice.getText()));
        dish.setMenuId(((Menu) cbxDish.getSelectedItem()).getId());
        dish.setStatus(dishStatus1.isSelected());
        dishDAO.edit(dish);
        loadDishList(null);
    }

    @Override
    public void doDeleteDish(int id) {
        int dishId = (int) tblDish.getValueAt(tblDish.getSelectedRow(), 0);
        dishDAO = new DishDAOImp();
        dishDAO.remove(dishId);
        loadDishList(null);
    }

    @Override
    public void findDish(String name) {
        loadDishList(name);
    }

    @Override
    public void AddDrink(JTextField txtDrinkName, JTextField txtDrinkPrice, JComboBox<Menu> cbxDrink, JRadioButton statusDrink1, JRadioButton statusDrink2) {
        String name = txtDrinkName.getText();
        float price = Float.parseFloat(txtDrinkPrice.getText());
        int menuId = ((Menu) cbxDrink.getSelectedItem()).getId();
        boolean status = true;
        if (statusDrink1.isSelected()) {
            status = true;
        } else {
            status = false;
        }
        drink = new Drink(name, price, menuId, status);
        drinkDAO = new DrinkDAOImp();
        drinkDAO.add(drink);
        loadDrinkList(null);
    }

    @Override
    public void EditDrink(int id, JTextField txtName, JTextField txtPrice, JComboBox<Menu> cbxDrink, JRadioButton statusDrink1, JRadioButton statusDrink2) {
        drink = new Drink();
        drinkDAO = new DrinkDAOImp();
        drink.setId(this.drinkId);
        drink.setName(txtName.getText());
        drink.setPrice(Float.parseFloat(txtPrice.getText()));
        drink.setMenuId(((Menu) cbxDrink.getSelectedItem()).getId());
        drink.setStatus(statusDrink1.isSelected());
        drinkDAO.edit(drink);
        loadDrinkList(null);
    }

    @Override
    public void removeDrink(int id) {
        int drinkId = (int) tblDrink.getValueAt(tblDrink.getSelectedRow(), 0);
        drinkDAO = new DrinkDAOImp();
        drinkDAO.remove(drinkId);
        loadDrinkList(null);
    }

    @Override
    public void findDrink(String name) {
        loadDrinkList(name);
    }

}
