/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.qlnh.gui.employee;

import com.toedter.calendar.JDateChooser;
import bkap.qlnh.dao.EmployeeDAOImp;
import bkap.qlnh.dao.RoleDAOImp;
import bkap.qlnh.entities.Employee;
import bkap.qlnh.entities.Role;
import bkap.qlnh.gui.mainframe.IFDelete;
import bkap.qlnh.gui.mainframe.IFFind;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import bkap.qlnh.util.DConnection;
import bkap.qlnh.util.Validation;

/**
 *
 * @author ntan2
 */
public class IFEmployee extends javax.swing.JInternalFrame implements bkap.qlnh.gui.mainframe.IFDelete.CallbackDelete, bkap.qlnh.gui.mainframe.IFFind.CallbackSearch  {

    /**
     * Creates new form IFEmployee
     */
    int id;
    EmployeeDAOImp empDAO;
    Validation v;
//    List<Employee> lstEmp = empDAO.lstEmployee();

    public IFEmployee() {
        initComponents();
        loadRole();
        loadList(null);
        tblEmployee.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                detail();
            }
        });
    }

    private void loadRole() {
        ArrayList<Role> lstRole = new ArrayList<>();
        lstRole.removeAll(lstRole);
        DefaultComboBoxModel<Role> dcbm = new DefaultComboBoxModel<Role>();
        ResultSet rs = DConnection.executeQuery("select*from tblRole");
        try {
            while (rs.next()) {
                Role r = new Role();
                r.setId(rs.getInt("id"));
                r.setName(rs.getString("name"));
                lstRole.add(r);
                dcbm.addElement(r);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IFEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbxRole.setModel(dcbm);
    }

    private void loadList(String name) {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        EmployeeDAOImp empDAO = new EmployeeDAOImp();
        List<Employee> lstEmp = new ArrayList<>(empDAO.lstEmployee(name));
        for (Employee e : lstEmp) {
            String status = "";
            if (e.isStatus() == true) {
                status = "Đang làm";
            } else {
                status = "Nghỉ";
            }
            model.addRow(new Object[]{e.getId(), e.getName(), e.getAge(), e.getEmail(),
                e.getPhone(), e.getAddress(), e.getRoleName(), new Date(e.getStartDate().getTime() + 172800000), e.getWorkTime(),
                e.getRate(), e.getSalary(), e.getPassword(), status});
        }
        tblEmployee.setModel(model);
    }

    private void detail() {
        int selectRow = tblEmployee.getSelectedRow();
        if (selectRow >= 0) {
            int id = (int) tblEmployee.getValueAt(selectRow, 0);
            EmployeeDAOImp empDAO = new EmployeeDAOImp();
            Employee e = new Employee();
            RoleDAOImp roleDAO = new RoleDAOImp();
            e = empDAO.find(id);
            txtName.setText(e.getName());
            txtAge.setText(String.valueOf(e.getAge()));
            txtEmail.setText(e.getEmail());
            txtPhone.setText(e.getPhone());
            txtAddress.setText(e.getAddress());
            cbxRole.getModel().setSelectedItem((Object) roleDAO.find(e.getRoleId()));
            startDate.setDate(new Date(e.getStartDate().getTime() + 172800000));
            txtWT.setText(String.valueOf(e.getWorkTime()));
            txtRate.setText(String.valueOf(e.getRate()));
            txtSalary.setText(String.valueOf(e.getSalary()));
            txtPass.setText(e.getPassword());
            if (e.isStatus()) {
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton2.setSelected(true);
            }

            this.id = e.getId();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPLeft = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        cbxRole = new javax.swing.JComboBox<>();
        lblSD = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        lblWT = new javax.swing.JLabel();
        txtWT = new javax.swing.JTextField();
        lblRate = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbMess = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản lý nhân viên");

        jPanel6.setBackground(new java.awt.Color(101, 176, 19));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        tblEmployee.setBackground(new java.awt.Color(204, 204, 0));
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Tuổi", "Email", "SĐT", "Địa Chỉ", "Vị Trí", "Ngày Bắt Đầu", "Thời Gian", "Cấp Lương", "Lương", "Mật Khẩu", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 7, 16));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jPLeft.setBackground(new java.awt.Color(102, 153, 0));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Tên:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAge.setText("Tuổi:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPhone.setText("SĐT:");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Địa Chỉ:");

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRole.setText("Vị trí:");

        lblSD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSD.setText("Ngày Bắt Đầu:");

        lblWT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWT.setText("Thời gian làm:");

        lblRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRate.setText("Cấp lương:");

        lblSalary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSalary.setText("Lương:");

        lblPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPass.setText("Mật Khẩu:");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("Trạng Thái:");

        jRadioButton1.setBackground(new java.awt.Color(102, 153, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Đang làm");

        jRadioButton2.setBackground(new java.awt.Color(102, 153, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Nghỉ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(34, 215, 199));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_add_user_male_32px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(34, 215, 199));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_edit_property_32px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(34, 215, 199));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_shopping_basket_remove_32px.png"))); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(34, 215, 199));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_reset_32px.png"))); // NOI18N
        btnNew.setText("Tải lại");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(34, 215, 199));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_exit_32px.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(34, 215, 199));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/qlnh/icon/icons8_find_user_male_32px.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm theo tên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbMess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMess.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPLeftLayout = new javax.swing.GroupLayout(jPLeft);
        jPLeft.setLayout(jPLeftLayout);
        jPLeftLayout.setHorizontalGroup(
            jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLeftLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLeftLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPLeftLayout.createSequentialGroup()
                        .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress)
                            .addComponent(lblEmail)
                            .addComponent(lblSD)
                            .addComponent(lblName)
                            .addComponent(lblRate)
                            .addComponent(lblPass))
                        .addGap(18, 18, 18)
                        .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLeftLayout.createSequentialGroup()
                                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPLeftLayout.createSequentialGroup()
                                        .addComponent(txtPass)
                                        .addGap(58, 58, 58)
                                        .addComponent(lblStatus))
                                    .addGroup(jPLeftLayout.createSequentialGroup()
                                        .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(41, 41, 41)
                                        .addComponent(lblWT))
                                    .addGroup(jPLeftLayout.createSequentialGroup()
                                        .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName)
                                            .addComponent(txtEmail)
                                            .addComponent(txtAddress))
                                        .addGap(100, 100, 100)
                                        .addComponent(lblRole))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLeftLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLeftLayout.createSequentialGroup()
                                        .addComponent(txtRate)
                                        .addGap(87, 87, 87)
                                        .addComponent(lblSalary)))
                                .addGap(26, 26, 26)
                                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalary, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtWT, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxRole, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAge)
                                    .addComponent(txtPhone)
                                    .addGroup(jPLeftLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPLeftLayout.createSequentialGroup()
                                .addComponent(lbMess, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPLeftLayout.setVerticalGroup(
            jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole)
                    .addComponent(cbxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSD)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRate)
                    .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSalary)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass)
                    .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStatus)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addGap(9, 9, 9)
                .addComponent(lbMess, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove)
                    .addComponent(btnNew)
                    .addComponent(btnExit)
                    .addComponent(jButton1))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (txtName.getText().trim().isEmpty() && txtAge.getText().trim().isEmpty()
                && txtEmail.getText().trim().isEmpty() && txtPhone.getText().trim().isEmpty()
                && txtAddress.getText().trim().isEmpty() && txtWT.getText().trim().isEmpty()
                && txtRate.getText().trim().isEmpty() && txtSalary.getText().trim().isEmpty()
                && txtPass.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập đủ các trường");
        } else if (txtName.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập tên");
        } else if (txtAge.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập tuổi");
        } else if (!v.CheckNumeric(txtAge.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtEmail.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập email");
        } else if (!v.CheckEmail(txtEmail.getText())) {
            lbMess.setText("Email không hợp lệ");
        } else if (txtPhone.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập sđt");
        } else if (!v.CheckPhone(txtPhone.getText())) {
            lbMess.setText("Sđt không đúng");
        } else if (txtAddress.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập địa chỉ");
        } else if (txtWT.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập thời gian làm việc");
        } else if (!v.CheckNumeric(txtWT.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtRate.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập hệ số lương");
        } else if (!v.CheckNumeric(txtRate.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtSalary.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập lương");
        } else if (!v.CheckNumeric(txtSalary.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtPass.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập mật khẩu");
        } else {
            String name = txtName.getText();
            int age = Integer.parseInt(txtAge.getText());
            String email = txtEmail.getText();
            String phone = txtPhone.getText();
            String address = txtAddress.getText();
            int roleId = ((Role) cbxRole.getSelectedItem()).getId();

            float workTime = Float.parseFloat(txtWT.getText());
            float rate = Float.parseFloat(txtRate.getText());
            float salary = Float.parseFloat(txtSalary.getText());
            String password = txtPass.getText();
            boolean status = true;
            if (jRadioButton1.isSelected()) {
                status = true;
            } else {
                status = false;
            }
            Employee e = new Employee(name, age, email, phone, address, roleId, new Date(startDate.getDate().getTime()), workTime, rate, salary, password, status);
            EmployeeDAOImp empDAO = new EmployeeDAOImp();
            empDAO.add(e);
            loadList(null);
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        IFDelete IFD = new IFDelete(true, this);
        IFD.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (txtName.getText().trim().isEmpty() && txtAge.getText().trim().isEmpty()
                && txtEmail.getText().trim().isEmpty() && txtPhone.getText().trim().isEmpty()
                && txtAddress.getText().trim().isEmpty() && txtWT.getText().trim().isEmpty()
                && txtRate.getText().trim().isEmpty() && txtSalary.getText().trim().isEmpty()
                && txtPass.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập đủ các trường");
        } else if (txtName.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập tên");
        } else if (txtAge.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập tuổi");
        } else if (!v.CheckNumeric(txtAge.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtEmail.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập email");
        } else if (!v.CheckEmail(txtEmail.getText())) {
            lbMess.setText("Email không hợp lệ");
        } else if (txtPhone.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập sđt");
        } else if (!v.CheckPhone(txtPhone.getText())) {
            lbMess.setText("Sđt không đúng");
        } else if (txtAddress.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập địa chỉ");
        } else if (txtWT.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập thời gian làm việc");
        } else if (!v.CheckNumeric(txtWT.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtRate.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập hệ số lương");
        } else if (!v.CheckNumeric(txtRate.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtSalary.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập lương");
        } else if (!v.CheckNumeric(txtSalary.getText())) {
            lbMess.setText("Vui lòng nhập số");
        } else if (txtPass.getText().trim().isEmpty()) {
            lbMess.setText("Vui lòng nhập mật khẩu");
        } else {
            Employee e = new Employee();
            EmployeeDAOImp empDAO = new EmployeeDAOImp();
            e.setId(this.id);
            e.setName(txtName.getText());
            e.setAge(Integer.parseInt(txtAge.getText()));
            e.setEmail(txtEmail.getText());
            e.setPhone(txtPhone.getText());
            e.setAddress(txtAddress.getText());
            e.setRoleId(((Role) cbxRole.getSelectedItem()).getId());
            e.setStartDate(new Date(startDate.getDate().getTime()));
            e.setWorkTime(Float.parseFloat(txtWT.getText()));
            e.setRate(Float.parseFloat(txtRate.getText()));
            e.setSalary(Float.parseFloat(txtSalary.getText()));
            e.setPassword(txtPass.getText());
            e.setStatus(jRadioButton1.isSelected());
            empDAO.edit(e);
            loadList(null);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtName.setText("");
        txtAge.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        cbxRole.setSelectedIndex(0);
        startDate.setDate(null);
        txtWT.setText("");
        txtRate.setText("");
        txtSalary.setText("");
        txtPass.setText("");
        lbMess.setText(" ");
        loadList(null);
        JOptionPane.showMessageDialog(null, "Tải lại thành công");
// TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IFFind ef = new IFFind(true, this);
        ef.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Role> cbxRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPLeft;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMess;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSD;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblWT;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtWT;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doDelete(int id) {
        EmployeeDAOImp empDAO = new EmployeeDAOImp();
        empDAO.remove(this.id);
        loadList(null);
    }

    @Override
    public void doAction(String name) {
        loadList(name);
    }
}
